### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-mirenguerra#1]
Well done @mirenguerra  !!!

Here you have some tips to improve the exercise:

- [x] Improve the meta title of the page
- [x] Menu items should be clickable
- [x] Humanize text in `alt` attributes, a sentence without the underscore may do the trick
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Main section should fit 100% of the browser's height
- [x] Any time we set an absolute or fixed position on an HTML element we should also set a left/right or a top/bottom CSS properties so it will display properly
- [x] Center the menu horizontally (remember the browser adds padding and margin to some tags as `ul`)
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Download the Adalab logo to a proper folder (although it is ok to use an absolute path we are going to use relative paths to a project file)
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Avoid writing the name of the tags on the classes
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed try to finish the styles.
Go for the tablet styles, step by step.

Let me know if you have any doubts ;)

Go for it!!

**Comment by mirenguerra** [comment]
Thank so much, Nasiba!

I'll go for it earlier as posible and i'll tell you if i have doubts.

**Comment by mirenguerra** [comment]
Hi @nasivuela 

Finally I understood what I did not understand and I finished the mobile part.
I've got the mediaqueries too and now I'm fighting with the position of the menu items. I will keep looking for the way.

Thanks for the tips, I have found them very helpful.

**Comment by mirenguerra** [comment]
Hi @nasivuela !

I have finished the exercise. Could you take a look and tell me if is it ok? 

Thank you so much!

**Comment by nasivuela** [comment]
Ey @mirenguerra, I have unchecked some points:

- On CSS avoid tag selectors as `header` or `main` unless you are doing some reset.
- Your header is fixed, let's indicate `top` and `left` positions.

And here you have some new ones:
- [x] No need to add `width: 100%` to main. It does it naturally.
- [x] Try to improve the header styles. On the mobile version, the menu should not be soo close to the bottom. On the tablet version, the logo and the menu look too separated from the edges and it makes the header too tall. Look at the original design to try to improve it ;)

Also, remember to add the link to Github Pages to the main page of Github ;)

**Comment by mirenguerra** [comment]
Hi @nasivuela !

Here you are the ultimate version of the exercise. I hope it will be correct.

Thanks.

**Comment by nasivuela** [comment]
Awesome @mirenguerra !!! You go it :D

![](https://media.giphy.com/media/I8XaJ6ZEFHI3u/giphy.gif)
